name: Deploy Production

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Container image tag to deploy"
        required: true
      environment:
        description: "Target environment"
        required: true
        default: "production"
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build-and-push:
    name: Build & Push Image
    runs-on: ubuntu-latest

    env:
      APP_NAME: daily-emr

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'af-south-1' }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run lint
        run: npm run lint

      - name: Run typecheck
        run: npm run typecheck

      - name: Build production bundle
        run: |
          set -o pipefail
          npm run build | tee build.log
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.event.inputs.image_tag || github.sha }}
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.APP_NAME }}:${IMAGE_TAG} .
          echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.APP_NAME }}:${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Push Docker image
        run: docker push $IMAGE_URI

      - name: Write image URI artifact
        run: echo "$IMAGE_URI" > image-uri.txt

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-uri
          path: image-uri.txt

  deploy:
    name: Terraform Apply
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-uri

      - name: Extract image URI
        id: image
        run: |
          IMAGE_URI=$(cat image-uri.txt)
          echo "uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "tag=${IMAGE_URI##*:}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'af-south-1' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: infra/terraform
        run: |
          set -o pipefail
          terraform plan -input=false -out=tfplan \
            -var="environment=${{ github.event.inputs.environment || 'production' }}" \
            -var="container_image_tag=${{ steps.image.outputs.tag }}" \
            -var="database_username=${{ secrets.DB_USERNAME }}" \
            -var="database_password=${{ secrets.DB_PASSWORD }}" \
            -var="acm_certificate_arn=${{ secrets.ACM_CERTIFICATE_ARN }}" | tee terraform-plan.log

      - name: Upload terraform plan log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-log
          path: infra/terraform/terraform-plan.log

      - name: Terraform Apply
        if: github.ref == 'refs/heads/production' || github.event_name == 'workflow_dispatch'
        working-directory: infra/terraform
        run: terraform apply -input=false tfplan

      - name: Notify success
        if: success()
        run: echo "Deployment succeeded for image ${{ steps.image.outputs.uri }}"

      - name: Notify failure
        if: failure()
        run: echo "Deployment failed" && exit 1
